static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"cs\">\n"
"<meta charset=\"utf-8\">\n"
"<title>Ovládání kamery</title>\n"
"<style>#controls{text-align:center;margin:12px 0}#viewer{text-align:center}button{margin:0 6px}label{margin-left:12px}</style>\n"
"<body>\n"
"<div id=\"controls\">"
"<button id=\"btn-jpeg\">Získej JPEG</button>"
"<button id=\"btn-mjpeg-start\">Nastartuj MJPEG</button>"
"<button id=\"btn-mjpeg-stop\">Zastav MJPEG</button>"
"<label>Kvalita <span id=\"qv\">50</span>%</label>"
"<input id=\"q\" type=\"range\" min=\"0\" max=\"100\" value=\"50\">"
"</div>\n"
"<div id=\"viewer\"></div>\n"
"<script>"
"const v = document.getElementById('viewer');"
"const bJ= document.getElementById('btn-jpeg');"
"const bS= document.getElementById('btn-mjpeg-start');"
"const bT= document.getElementById('btn-mjpeg-stop');"
"const q = document.getElementById('q');"
"const qv= document.getElementById('qv');"
"let img=null;"
"const BLANK='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';" /* 1x1 GIF */
"function qval(){return q.value|0;}"
"function clr(){"
"  if(img){"
"    try{ img.src = BLANK; }catch(e){}"  /* Přepnutí na jiný obrázek zatručí ukončení HTTP spojení, které potřebujeme pro zastavení streamu */
"    img.remove();"
"    img=null;"
"  }"
"}"
"function setIdle(){ bJ.disabled=false; bS.disabled=false; bT.disabled=true; }"
"function setMJPEG(){ bJ.disabled=true;  bS.disabled=true;  bT.disabled=false; }"
"q.oninput=()=>qv.textContent=q.value;"
"setIdle();"
"bJ.onclick=()=>{ if(bJ.disabled) return; clr(); img=new Image(); img.src='/capture-jpeg?quality='+qval()+'&t='+Date.now(); v.appendChild(img); };"
"bS.onclick=()=>{ if(bS.disabled) return; setMJPEG(); clr(); img=new Image();"
"  img.src = location.protocol+'//'+location.hostname+':81/?quality='+qval()+'&t='+Date.now();"
"  v.appendChild(img);"
"};"
"bT.onclick=()=>{ if(bT.disabled) return; clr(); setIdle(); };"
"window.addEventListener('beforeunload', clr);"
"</script>\n"
"</body>\n"
"</html>\n";
